###### PRODUCT REQUESTS #####

###
GET http://localhost:3000/products.json?category=Food
###
GET http://localhost:3000/products.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2NDc5NzQ3MjN9.HXc0squic8mDp7aMGVP2grNwnv14KZ96VRPeC_6o-14
###
GET http://localhost:3000/products/22.json
###
POST http://localhost:3000/products.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2NDgxNDA0NTl9.C7ntfLjgvIudSGASCb21r-Gd7tmdFosm0sQ5ccfOvC4
content-type: application/json

{
  "name": "omega squeaker 22",
  "price": 3,
  "description": "ahhhhhh i dont think this will work lol",
  "stock": 27,
  "supplier_id": 3,
  "input_images": ["https://cdn.shopify.com/s/files/1/1083/2612/products/JapaneseKitKat_Hojicha_Tabling_1200x1200.jpg", "https://cdn.shopify.com/s/files/1/1083/2612/products/JapaneseKitKat_Hojicha_Tabling_1200x1200.jpg"]
}

###
PATCH http://localhost:3000/products/24.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2NDgxNDA0NTl9.C7ntfLjgvIudSGASCb21r-Gd7tmdFosm0sQ5ccfOvC4
content-type: application/json

{
  "name": "squeakalina",
  "price": 599,
  "description": "Engineered for whole-home, deep cleaning with suction power, run time and tools designed to deep clean your whole home. Dyson DLS™ technology automatically senses and adapts to changes in floor type to extend run time and provide the right balance of power and run time when you need it.",
  "stock": 3
}

###
DELETE http://localhost:3000/products/22
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2NDgxNDA0NTl9.C7ntfLjgvIudSGASCb21r-Gd7tmdFosm0sQ5ccfOvC4

###### SUPPlIER REQUESTS #####

GET http://localhost:3000/suppliers.json
###
GET http://localhost:3000/suppliers/1.json
###
POST http://localhost:3000/suppliers.json
content-type: application/json

{
  "name": "p"
}

###
PATCH http://localhost:3000/suppliers/9.json
content-type: application/json

{
  "name": "squeaker",
  "email": "test@test.com"
}

###
DELETE http://localhost:3000/suppliers/9

##### USERS REQUESTS #####

### Users create (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "regina",
  "email": "tactician@grams.com",
  "password": "sandalphonluvr2",
  "password_confirmation": "sandalphonluvr2"
}

### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "tactician@grams.com",
  "password": "sandalphonluvr2"
}

### Orders Create

POST http://localhost:3000/orders.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2NDg1Nzc5OTB9.uzVT_gfkGhfnbl7H-cfoiu2JIyRCew2zUFyk0s9j3Qk
# Content-Type: application/json

# {
#   "product_id": 17,
#   "quantity": 6
# }

### Orders Show

GET http://localhost:3000/orders/5.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2NDg1NzA0MjB9.O6PwzOLQTDJltV1wVyccwi3m9hAf3r3hLwnPm1YGJXc

### Orders Index

GET http://localhost:3000/orders.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2NDg1Nzc5OTB9.uzVT_gfkGhfnbl7H-cfoiu2JIyRCew2zUFyk0s9j3Qk

### CP Create Product

POST http://localhost:3000/carted_products.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2NDg1Nzc5OTB9.uzVT_gfkGhfnbl7H-cfoiu2JIyRCew2zUFyk0s9j3Qk
Content-Type: application/json

{
  "product_id": 1,
  "quantity": 4
}

### CP View Products

GET http://localhost:3000/carted_products.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2NDg1Nzc5OTB9.uzVT_gfkGhfnbl7H-cfoiu2JIyRCew2zUFyk0s9j3Qk

### CP Update Product

PATCH http://localhost:3000/carted_products/9.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2NDg1Nzc5OTB9.uzVT_gfkGhfnbl7H-cfoiu2JIyRCew2zUFyk0s9j3Qk
Content-Type: application/json

{
  "quantity": 10
}
### CP Delete Product
DELETE http://localhost:3000/carted_products/9
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2NDg1Nzc5OTB9.uzVT_gfkGhfnbl7H-cfoiu2JIyRCew2zUFyk0s9j3Qk