GET http://localhost:3000/products.json
###
GET http://localhost:3000/products/11.json
###
POST http://localhost:3000/products.json
content-type: application/json

{
  "name": "testname",
  "price": 2,
  "image_url": "testimg",
  "description": "testdesc",
  "stock": 2
}

###
PATCH http://localhost:3000/products/17.json
content-type: application/json

{
  "name": "hi",
  "price": 599.99,
  "image_url": "http://mobileimages.lowes.com/productimages/11061d23-6373-40b1-b6e3-fc91e4f56145/10722033.jpg",
  "description": "Engineered for whole-home, deep cleaning with suction power, run time and tools designed to deep clean your whole home. Dyson DLS™ technology automatically senses and adapts to changes in floor type to extend run time and provide the right balance of power and run time when you need it.",
  "stock": 3
}

###
DELETE http://localhost:3000/products/15