# Image.create!([
#   {url: "http://image.com/febreeze", product_id: 1},
#   {url: "http://image.com/macncheese", product_id: 2},
#   {url: "http://image.com/kitkat", product_id: 3}
# ])

# Supplier.create!([
#   {name: "Example 1", email: "Example@One.com", phone: "1011011001"},
#   {name: "Example 2", email: "Example@Two.com", phone: "2022022002"},
#   {name: "Example 3", email: "Example@Three.com", phone: "3033033003"},
# ])

# Product.create!([
#   {name: "Febreze Blossom & Breeze Vaporizador 300 Ml", price: "7.99", image_url: "https://m.media-amazon.com/images/I/418BiWuRVUL._AC_SX679_.jpg", description: "Febreze AIR doesn't just mask odors, it cleans away odors with OdorClear Technology, leaving your air with a light, fresh scent. So when something stinky gets in your way, reach for Febreze AIR to eliminate odors on the spot.", stock: 16},
#   {name: "Kraft Macaroni & Cheese", price: "3.99", image_url: "https://i5.walmartimages.com/asr/2c10224e-7fa9-4748-b0cb-7608f47a0e5e.4d39334f838afac1a7c541fd41bc969a.jpeg", description: "Kraft Macaroni and Cheese has no artificial flavors, preservatives or dyes. But it still has the great taste you know and love. Most of our mac and cheese products have 10% of the recommended daily value for calcium and 8 or 9 grams of protein.", stock: 8},
#   {name: "Kit Kat", price: "1.99", image_url: "https://i5.walmartimages.com/asr/ceaefb20-66fd-4e8d-afa4-721bd148be50_1.caca1089569b0608419aeab7d1ec7a73.jpeg?odnHeight=612&odnWidth=612&odnBg=FFFFFF", description: "A KIT KAT® bar is made of three layers of wafer separated and covered by an outer layer of chocolate. The standard bars consist of four pieces, called fingers, and each finger can be snapped from the bar as an individual piece.", stock: 6},
#   {name: "Blue Yeti USB Microphone (Silver)", price: "99.99", image_url: "https://www.bhphotovideo.com/cdn-cgi/image/format=auto,fit=scale-down,width=500,quality=95/https://www.bhphotovideo.com/images/images500x500/Blue_YETI_Yeti_Multi_Pattern_USB_Microphone_1634135734_857749.jpg", description: "A simple, yet powerfully effective tool for content creators, the Blue Microphones Yeti is a USB mic offering a broadcast-quality sound, a rugged design, and multiple recording modes to suit your needs. The Yeti, offfered here in a silver finish, has become a go-to mic for people who record podcasts, and who stream on YouTube, Twitch, Facebook Live, and other similar platforms.", stock: 4},
#   {name: "Dyson V11 Animal Cordless Stick Vacuum", price: "599.99", image_url: "http://mobileimages.lowes.com/productimages/11061d23-6373-40b1-b6e3-fc91e4f56145/10722033.jpg", description: "Engineered for whole-home, deep cleaning with suction power, run time and tools designed to deep clean your whole home. Dyson DLS™ technology automatically senses and adapts to changes in floor type to extend run time and provide the right balance of power and run time when you need it.", stock: 2},
#   {name: "Gatorade", price: "2.99", image_url: "https://www.kroger.com/product/images/large/front/0005200032481", description: "Gatorade is a brand of flavored non-carbonated sports drinks manufactured by the Quaker Oats Company, now a division of PepsiCo. Intended for consumption during physically active occasions, Gatorade beverages are formulated to rehydrate and replenish fluid, carbohydrates and electrolytes.", stock: 10},
#   {name: "Roomba", price: "299.99", image_url: "https://store.irobot.com/on/demandware.static/-/Sites-master-catalog-irobot/default/dwb9ab95d5/images/large/R860020.jpg", description: "Roomba is a series of autonomous robotic vacuum cleaners sold by iRobot. Introduced in September 2002, they have a set of sensors that enable them to navigate the floor area of a home. These sensors can detect the presence of obstacles, particularly dirty spots on the floor, and steep drops (e.g. to avoid falling down stairs).", stock: 3},
#   {name: "Goupsky Roller Skate Shoes for Women (Blue)", price: "79.99", image_url: "https://m.media-amazon.com/images/I/61HBBkjOiQL._AC_SL1001_.jpg", description: "58mm wheels give faster roll time for extreme speed.83A urethane is medium soft and grippy for everything from concrete to asphalt. Great for cruising through the park, skating along the boardwalk or showing off in your neighborhood, these skates can take the terrain.", stock: 1}
# ])